# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Protect your secrets from AI coding agents via a local credential-injecting proxy"
  homepage "https://github.com/getveil/veil"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getveil/veil/releases/download/v0.1.0/veil_0.1.0_darwin_amd64.tar.gz"
      sha256 "899807328861bd98904cc0567b70930a1fc5f2ce40c23596c50789a3906a7f27"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getveil/veil/releases/download/v0.1.0/veil_0.1.0_darwin_arm64.tar.gz"
      sha256 "c6dd7a6044a75dca6bf22a11213529efeec28b858f455390db29ef8ca2bb9107"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.0/veil_0.1.0_linux_amd64.tar.gz"
      sha256 "23acf6f4b88c54da2842169822343785f91a92c57e24003a5da4ca90be1de1ea"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.0/veil_0.1.0_linux_arm64.tar.gz"
      sha256 "728be0c84d32b010de83e8b609aafd5b08e90ae52efafaf1ae6ea5a05c301cfc"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  test do
    assert_match "veil v#{version}", shell_output("#{bin}/veil --version")
  end
end
