# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Protect your secrets from AI coding agents via a local credential-injecting proxy"
  homepage "https://github.com/getveil/veil"
  version "0.1.0-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getveil/veil/releases/download/v0.1.0-rc1/veil_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "45a2b38688d8f104dafd69c8089b19017b700d78592ccffa999ee66c2070daa2"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getveil/veil/releases/download/v0.1.0-rc1/veil_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "28801fd64fffe2d151be0aea89a316c3fc5a7b16cff3d36f2261dfc67083e368"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.0-rc1/veil_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "a9c74d3075cb81debe19bb190ae4a828aa7bb75b81c8ca58111b5559f6812293"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.0-rc1/veil_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "1f35e2c1539ec9ff4adf20296bf99db68c396100430f9c5731c7b40e03f3e840"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  test do
    assert_match "veil v#{version}", shell_output("#{bin}/veil --version")
  end
end
