# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Protect your secrets from AI coding agents via a local credential-injecting proxy"
  homepage "https://github.com/getveil/veil"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getveil/veil/releases/download/v0.1.1/veil_0.1.1_darwin_amd64.tar.gz"
      sha256 "a9728fc8a3f6de73675fbb2823c57447ff7ed95e638adf3676370da0f10120e8"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getveil/veil/releases/download/v0.1.1/veil_0.1.1_darwin_arm64.tar.gz"
      sha256 "b7af8d110423bff9a5e708beaa2084bc98ca024479b9cb1ef748fe758f72abc7"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.1/veil_0.1.1_linux_amd64.tar.gz"
      sha256 "0ad670b79c24329b4f0bbef1d5fde3d099f70a5f5f1b40ceaeb9a8d29f62b996"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.1.1/veil_0.1.1_linux_arm64.tar.gz"
      sha256 "f4126632730aef0cb40ae630c979d0a5e59a83efe1582bdf3d0dcdfb5375d644"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  test do
    assert_match "veil v#{version}", shell_output("#{bin}/veil --version")
  end
end
