# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Protect your secrets from AI coding agents via a local credential-injecting proxy"
  homepage "https://github.com/getveil/veil"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getveil/veil/releases/download/v0.2.0/veil_0.2.0_darwin_amd64.tar.gz"
      sha256 "06b74049912086a82f30a6aca19c1b79e9b2c7e1c1fa01b017de598765922887"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getveil/veil/releases/download/v0.2.0/veil_0.2.0_darwin_arm64.tar.gz"
      sha256 "59722d0edf04bcb2f80a9917ff660d259f0fd02b19c263b279b473bd4ad15118"

      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.2.0/veil_0.2.0_linux_amd64.tar.gz"
      sha256 "753a7300040692da961af968e165eb32390c8eb7f3df61e6cdd4b61c2a113344"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getveil/veil/releases/download/v0.2.0/veil_0.2.0_linux_arm64.tar.gz"
      sha256 "fba97cc5741af8468db1c74d8efa61957e467591ffe36ba660e4e4a86b82df63"
      define_method(:install) do
        bin.install "veil"
        bash_completion.install "completions/veil.bash" => "veil"
        zsh_completion.install "completions/_veil"
        fish_completion.install "completions/veil.fish"
      end
    end
  end

  test do
    assert_match "veil v#{version}", shell_output("#{bin}/veil --version")
  end
end
